#import "@preview/supercharged-dhbw:3.4.1": *

= Business Understanding <chap:business_understanding>
Der Anlass für dieses Projekt und somit auch für die vorliegende Arbeit entstand aus dem Bestreben der Abteilung für Kundenberatung rund um die SAP Business Technology Platform (BTP), den internen Aufwand bei der Erstellung von CI/CD-Pipelines für CAP-Applikationen zu reduzieren. Besonders im Kontext von Kunden-Demonstrationen, bei denen regelmäßig neue CAP-Projekte erstellt werden, zeigte sich, dass die manuelle Konfiguration der notwendigen Pipeline-Dateien zeitintensiv, fehleranfällig und wenig skalierbar ist. Unsere internen Beobachtungen decken sich mit Ergebnissen aus der Literatur, wonach manuell konfigurierte CI/CD-Prozesse fehleranfällig und ineffizient sein können @RedHat2025.

Interne Erfahrungen bestätigten, dass ein Großteil der Arbeitszeit für wiederkehrende, manuelle Konfigurationsaufgaben aufgewendet wird, obwohl diese Aufgaben ein hohes Automatisierungspotenzial aufweisen. Studien zeigen, dass etwa 60% der IT-Tätigkeiten aus solchen Routineaufgaben bestehen, die mit modernen Automatisierungstechnologien effizienter und qualitativ konsistenter ausgeführt werden könnten. Die Automatisierung von Prozessen führt dabei nicht nur zu einer signifikanten Reduktion menschlicher Fehler, sondern schafft auch Freiräume für kreative und strategische Tätigkeiten. @Kergassner2012

Vor diesem Hintergrund entstand die Idee und das Ziel, einen KI-gestützten Agenten zu entwickeln, der die Erstellung von CI/CD-Pipelines automatisiert. Ein solcher Ansatz ist sowohl für die SAP SE als auch für die beteiligten Abteilungen von strategischem Interesse, da er Effizienzgewinne, Qualitätssteigerungen und Ressourceneinsparungen verspricht. Durch die Automatisierung der Pipeline-Generierung lassen sich Standardprozesse beschleunigen und konsistente Deployment-Konfigurationen gewährleisten, was letztlich die Time-to-Cloud für CAP-Projekte reduziert.

Die angestrebte Lösung mittels eines KI-Agenten soll Entwickler:innen gezielt bei der Arbeit unterstützen, indem sie den manuellen Aufwand minimiert und technische Details der Pipeline-Konfiguration übernimmt. Ziel ist es, dass der Agent lediglich die GitHub-Repository-URL eines Projekts entgegennimmt, relevante Parameter und Dateien automatisch analysiert und daraus eine funktionsfähige CI/CD-Pipeline generiert. \ Diese soll als Pull Request bereitgestellt werden, sodass Entwickler:innen sie vor der Integration prüfen und anpassen können. Der Agent agiert damit als intelligentes Assistenzsystem, das die Produktivität erhöht, ohne den Menschen aus dem Prozess auszuschließen. In dieser Pull Request können dann Entwickler:innen durch GitHub Actions die generierte Pipeline validieren und bei Bedarf modifizieren. 

Als Evaluationsmethode wird in dieser Arbeit das Human-as-a-Judge-Verfahren eingesetzt. Dabei erfolgt die Bewertung der generierten Pipelines durch mich in der Rolle des Human Judge, unterstützt durch erfahrene Entwickler:innen aus der Abteilung. Diese beurteilen die erzeugten Ergebnisse hinsichtlich Funktionalität, Korrektheit und Effizienz.\
Die Wahl einer qualitativen, expertenbasierten Evaluationsmethode begründet sich durch die fehlende Verfügbarkeit gelabelter Vergleichsdaten. Es existieren keine Referenz-Pipelines, mit denen die generierten Artefakte objektiv, z.B. mittels S-BERT oder ROUGE-N verglichen werden könnten. Zudem steht im Vordergrund, den praktischen Nutzen und die Umsetzbarkeit der Lösung im realen Entwicklungskontext zu bewerten, was durch menschliche Facheinschätzungen besser abgebildet werden kann als durch rein numerische Kennzahlen.\
Quantitative Metriken, etwa zur Laufzeit oder Codezeilenlänge, werden in diesem Kontext nur ergänzend betrachtet, da sie die Qualität der Pipeline (z. B. im Hinblick auf die Fehlerfreiheit) nicht angemessen widerspiegeln würden. Ziel der Evaluation ist daher nicht die Erreichung eines bestimmten numerischen Schwellenwerts, sondern der Nachweis funktionaler Vollständigkeit (die Pipeline kann erfolgreich ausgeführt werden), syntaktischer Korrektheit (valide YAML-Struktur) und praktischer Effizienz (keine unnötigen Build- oder Deployment-Schritte).
