#import "@preview/supercharged-dhbw:3.4.1": *

= Business Understanding <chap:business_understanding>
Der Anlass für dieses Projekt und somit auch für die vorliegende Arbeit entstand aus dem Bestreben der Abteilung für Kundenberatung rund um die SAP Business Technology Platform (BTP), den internen Aufwand bei der Erstellung von CI/CD-Pipelines für CAP-Applikationen zu reduzieren. Besonders im Kontext von Kunden-Demonstrationen, bei denen regelmäßig neue CAP-Projekte erstellt werden, zeigte sich, dass die manuelle Konfiguration der notwendigen Pipeline-Dateien zeitintensiv, fehleranfällig und wenig skalierbar ist. Unsere internen Beobachtungen decken sich mit Ergebnissen aus der Literatur, wonach manuell konfigurierte CI/CD-Prozesse fehleranfällig und ineffizient sein können @RedHat2025.

Interne Erfahrungen bestätigten, dass ein Großteil der Arbeitszeit für wiederkehrende, manuelle Konfigurationsaufgaben aufgewendet wird, obwohl diese Aufgaben ein hohes Automatisierungspotenzial aufweisen. Studien zeigen, dass etwa 60% der IT-Tätigkeiten aus solchen Routineaufgaben bestehen, die mit modernen Automatisierungstechnologien effizienter und qualitativ konsistenter ausgeführt werden könnten. Die Automatisierung von Prozessen führt dabei nicht nur zu einer signifikanten Reduktion menschlicher Fehler, sondern schafft auch Freiräume für kreative und strategische Tätigkeiten. @Kergassner2012

Vor diesem Hintergrund entstand die Idee und das Ziel, einen KI-gestützten Agenten zu entwickeln, der die Erstellung von CI/CD-Pipelines automatisiert. Ein solcher Ansatz ist sowohl für die SAP SE als auch für die beteiligten Abteilungen von strategischem Interesse, da er Effizienzgewinne, Qualitätssteigerungen und Ressourceneinsparungen verspricht. Durch die Automatisierung der Pipeline-Generierung lassen sich Standardprozesse beschleunigen und konsistente Deployment-Konfigurationen gewährleisten, was letztlich die Time-to-Cloud für CAP-Projekte reduziert.

Die angestrebte Lösung mittels eines KI-Agenten soll Entwickler:innen gezielt bei der Arbeit unterstützen, indem sie den manuellen Aufwand minimiert und technische Details der Pipeline-Konfiguration übernimmt. Ziel ist es, dass der Agent lediglich die GitHub-Repository-URL eines Projekts entgegennimmt, relevante Parameter und Dateien automatisch analysiert und daraus eine funktionsfähige CI/CD-Pipeline generiert. \ Diese soll als Pull Request bereitgestellt werden, sodass Entwickler:innen sie vor der Integration prüfen und anpassen können. Der Agent agiert damit als intelligentes Assistenzsystem, das die Produktivität erhöht, ohne den Menschen aus dem Prozess auszuschließen. In dieser Pull Request können dann Entwickler:innen durch GitHub Actions die generierte Pipeline validieren und bei Bedarf modifizieren. 

Zur Beurteilung des Agenten wird ein qualitatives, expertenbasiertes Verfahren (Human-as-a-Judge) eingesetzt, bei dem die generierten Pipelines durch mich sowie erfahrene Entwickler:innen der Abteilung bewertet werden. Der Erfolg bemisst sich dabei an drei zentralen, praxisnahen Kriterien: funktionale Vollständigkeit (die Pipeline lässt sich erfolgreich ausführen), syntaktische Korrektheit (valide YAML-Struktur) und praktische Effizienz (keine unnötigen Build- oder Deployment-Schritte). Eine detaillierte Ausgestaltung und methodische Begründung dieses Bewertungsverfahrens erfolgt im Evaluationskapitel.

